version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: classroomDB
      MYSQL_USER: yungkooi
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password